language: node_js

node_js:
  - "stable"

cache:
  directories:
  - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKENS  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
  local_dir: public
  keep-history: true

before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
after_success:
  - "npm run deploy"

after_script:
  - bash ./telegram_notification.sh

notifications:
  slack:
    rooms:
      - wiredcraft:xC3ZVpNi5EZGX2XLxd4a2HFv
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}. <https://portfolio.uetuluk.xyz|CHECK IT OUT>"
